[package]
name = "chip8"
version = "0.1.0"
authors = ["Grayson Hay <me@russellhay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
log = "0.4.8"
pretty_env_logger = "0.4.0"
